### ISSUE TITLE
`--azureml` flag not working as expected

### ISSUE THREAD

**Issue by peterhessey** [microsoft/hi-ml#690]
It seems that the `--azureml` flag is not working, at least not in the the [first steps docs](https://hi-ml.readthedocs.io/en/latest/first_steps.html) explains it.

If I try running my script with the `--azureml` flag it runs locally, unless I specify `submit_to_azureml=True` in the call to `submit_to_azureml_if_needed()`. After having a look at the code in [himl.py](https://github.com/microsoft/hi-ml/blob/main/hi-ml-azure/src/health_azure/himl.py#L834) this behaviour makes sense, as the code is run locally `if not submit_to_azureml`, where `submit_to_azureml` is set to `None` even if the `--azureml` flag is used. 

Not sure if I'm missing something here, but it appears the logic for checking for `--azureml` in `sys.argv` is missing.

**Comment by ant0nsc** [comment]
Expected behaviour on local box with `--azureml`:
* Script runs on the local box, with `--azureml` on the commandline
* Submit function will prepare datasets if needed
* Then create a snapshot of the current codebase and send it to AzureML
* Create a `job` or `Run` from the codebase that invokes the current script, send that to AzureML. Commandline arguments for that job in AzureML should be the same as the current script, possibly minus the `--azureml` flag
* Stop execution by calling `exit` - AzureML will now take over and run the script in the cloud

Expected behaviour in AzureML:
* `submit_to_azure_if_needed` function returns a `RunInfo` object that contains paths to mounted datasets

Expected behaviour on local box without `--azureml`:
* `submit_to_azure_if_needed` function returns a `RunInfo` object that contains paths to either mounted datasets or the `local_path`(?) field of a `DatasetConfig` object

**Comment by peterhessey** [comment]
The test `test_submit_to_azure_if_needed_azure_return()` in `testazure/testazure/test_himl.py:564` is coded to test for incorrect behaviour. if the `--azureml` flag is passed then we'd expect the program to exit entirely with no run info returned.
